name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
    name: OTP ${{matrix.pair.otp}} / Elixir ${{matrix.pair.elixir}}
    strategy:
      fail-fast: false
      matrix:
        include:
          - pair:
              otp: 21.3
              elixir: 1.10.2
          - pair:
              otp: 24.2
              elixir: 1.13.2
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-elixir@v1
        with:
          otp-version: ${{matrix.pair.otp}}
          elixir-version: ${{matrix.pair.elixir}}
      - name: Conform
        uses: talos-systems/conform@v0.1.0-alpha.19
      - name: Install → Compile dependencies
        run: |
          MIX_ENV=test mix deps.get
          MIX_ENV=test mix deps.compile
          MIX_ENV=test mix compile
      - name: Start epmd
        run: |
          epmd -daemon
      - name: Run tests
        run: |
          MIX_ENV=test mix test
  
